### ISSUE TITLE
Avoid dumping and parsing JSON for jsonb field

### ISSUE THREAD

**Issue by maria-kachusova** [estepnv/leafy#2]
We use Leafy with ActiveRecord and Postgres. Our `leafy_data` type is jsonb. `leafy_fields` and `leafy_values` work fine.

But sometimes we need to use data from `leafy_data` field directly in SQL queries. Because of serialization to JSON text before saving to the database Postgres thinks it is a string and can't parse it or convert to JSON type. So the problem is that we can't use `leafy_data` in SQL queries.

I think, one of the possible solutions is to modify `FieldValueCollection` `dump` and `load` to not use json serialization for ActiveRecord json/jsonb type fields. What do you think about this?

```ruby
Leafy::FieldValueCollection

def self.dump(field_values_collection, json_serialization = true)
  collection = field_values_collection
                 .map { |field_value| [field_value.id, field_value.raw] }
                 .to_h

  json_serialization ? JSON.dump(collection) : collection
end

def self.load(leafy_fields, data, json_serialization = true)
  Leafy::FieldValueCollection.new(
      leafy_fields,
      json_serialization ? JSON.load(data) : data
  )
end
```
And call it like that:
```ruby
Leafy::Mixin::ActiveRecord::Fields::InstanceMethods

def leafy_field_values
  :Leafy::FieldValueCollection.load(leafy_fields, leafy_data || "{}", activerecord_json_column?)
end
```

**Comment by estepnv** [comment]
@maria-kachusova  https://github.com/estepnv/leafy/pull/3 looks like it should your issue
