### ISSUE TITLE
Uninitialized constant

### ISSUE THREAD

**Issue by sqlninja** [estepnv/leafy#5]
Any reason I'd be seeing this in my rails 6 app?
`NameError: uninitialized constant #<Class:0x00007ff1e9c351f8>::Leafy`

My Model has this:
```
class TeamContact < ApplicationRecord
  include Leafy::Mixin::Schema[:active_record]
 ...
end
```

**Comment by estepnv** [comment]
Hey there @sqlninja , pls try requiring it in initializer. I’ll appreciate it if you update readme

**Comment by sqlninja** [comment]
That seems to have gotten me past the issue. Thanks
[PR](https://github.com/estepnv/leafy/pull/6) submitted to update readme
